### PR TITLE
Imports 22102019

### PR DESCRIPTION
**Pull request by matentzn**
Imports refresh

### CODE REVIEW

**Comment by drseb** [comment]
why do we have to re-gen imports now?

**Comment by matentzn** [comment]
We dont; I just have a biweekly to do item to refresh HPO imports to keep them up to date; can move this to 'on request', I dont really mind. Up to you.

**Comment by drseb** [comment]
ah ok. just wanted to understand. previously we did it only when there changes upstream that made a re-gen necessary. what do you prefer?

**Comment by matentzn** [comment]
I think we have two options: 
1) I continue doing this biweekly thing. PRO: Its a regular thing that does not need communication overhead from anyone and everyone can just expect it to happen; I can plan it so wont interfere with other things. CONTRA: sometimes, people need to wait a week till their terms get updated.
2) I do it on demand. PRO: This may mean it will be considerably closer to when its needed, i.e. a new term was imported; it may be less often than 1), so theoretically less work; CONTRA: it requires someone to ping me; it may not happen on very short notice if conflicting with other things.

I am fine with either of these choices, with a very mild preference to 1).

**Comment by drseb** [comment]
Hmm. I think I prefer option 2. Also, keep in mind that you're not the only person who can generate the imports. Let's discuss on next call maybe

**Comment by matentzn** [comment]
Option 2 it is! :)

**Pull request merged**
