### PR TITLE
Removing all NCIT eq and adding them to external (importable) file

### PR DESCRIPTION
**Pull request by matentzn**
To move forward with organising the HP imports properly, we now removed all logical definitions with NCIT references in it from HP, and added them, entirely unchanged, to a new file called hp_ncit_eq.owl. The file can, if necessary, be easily imported into HP - for now they are separate until the neoplasm discussion is resolved. There is zero loss of information.

### CODE REVIEW

**Comment by matentzn** [comment]
@pnrobinson @drseb 
Please look [here](https://github.com/obophenotype/human-phenotype-ontology/pull/4331/files) and click on show diff to see what has been removed from hp-edit.owl. Everything removed has simply been moved to the second file, hp_ncit_eq.owl.

**Comment by matentzn** [comment]
(This should be merged soon in order to avoid conflicts with a changing Master branch)

**Comment by drseb** [comment]
I think this is a very safe route and we should merge. @pnrobinson ok?

**Comment by pnrobinson** [comment]
1+ let's go ahead!

**Comment by pnrobinson** [comment]
btw Nico please join the hp-editors list, I am not sure you saw the lock (I have not changed anything no worry..)

**Comment by matentzn** [comment]
Oh thanks oops you are right. I will join. But in any case I would generally never edit hp-edit.owl directly. Always through pull requests; so we should be safe.

**Pull request merged**
