### PR TITLE
DO NOT MERGE: experiment with shadowing NCIT classes in HPO

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
Sample:

screen shot 2016-06-09 at 4 27 00 pm

Note: can someone else try to load hp-edit.owl on this branch? Not sure why it doesn't work.

I get

```
2016-06-09 16:10:41.639 [pool-1-thread-1] INFO  AbstractOWLParser    URL connection input stream is compressed using gzip
2016-06-09 16:10:41.745 [pool-1-thread-1] INFO  OntologyLoader    Finished loading imported ontology at http://purl.obolibrary.org/obo/upheno/imports/chebi_import.owl
2016-06-09 16:10:41.745 [pool-1-thread-1] INFO  AutoMappedRepositoryIRIMapper    Imported ontology document http://purl.obolibrary.org/obo/upheno/imports/hsapdv_import.owl was not resolved to any documents defined in the ontology catalog.
2016-06-09 16:10:41.746 [pool-1-thread-1] INFO  OntologyLoader    Finished loading file:/Users/cjm/repos/human-phenotype-ontology/src/ontology/hp-edit.owl
2016-06-09 16:10:41.768 [AWT-EventQueue-0] ERROR OntologyLoader    An error occurred whilst loading the ontology at null. Cause: {}
2016-06-09 16:10:41.947 [AWT-EventQueue-0] INFO  OWLModelManagerImpl    Loading for ontology and imports closure successfully completed in 3333 ms
```

**Comment by balhoff** [comment]
I didn't have any problem loading hp-edit.owl from ncit-shadow with Protege 5.0.0 RC1.

**Comment by elviram** [comment]
I had issues with opening it with Protege 4.3.0
I have noticed this before. Files generated with Protege 5 do have issues with Protege 4.3.0, maybe even with other older ones (I have not checked).

**Comment by cmungall** [comment]
Thanks for trying

I get the error message with P5, it was generated using the owlapi 
v4.2.4, which should be what p5 uses

**Comment by mellybelly** [comment]
I can open neoplasm.owl and hp-edit.owl from this branch in P5b21 or P5, but I don't see the new import in hp-edit.

The file also loads from the URL fine for me, but only on my faster new machine with P5:
https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/ncit-shadow/src/ontology/hp-edit.owl

If I add the import I see both NCIT IDs and the new 'Neoplasm presence' terms

**Comment by mellybelly** [comment]
Also, we discussed pulling the subclass hierarchy from NCIT as the closure for the terms that are in the tab file, should I prune further in the tab file or wait until we have the closure?

**Comment by cmungall** [comment]
The module extraction should bring in all ancestors into ncit_import. Whether we want to shadow some or all intermediate classes is another issue. We can do something like algorithmically populate MRCAs

**Comment by drseb** [comment]
maybe I missed it, but how do we "merge" ncit and existing HP-classes? manually?

**Comment by mellybelly** [comment]
I'm getting errors now too, now that the import is added. Seems its because it is pointing at a purl that hasn't yet been declared.

**Comment by cmungall** [comment]
On 13 Jun 2016, at 1:29, Sebastian Köhler wrote:

> maybe I missed it, but how do we "merge" ncit and existing HP-classes? 
> manually?

This branch is an experiment in shadowing, so there would be no merge, 
these would be separate branches, ontologically and pragmatically.

The are pros and cons of this approach compared with a more aggressive 
merge-based approach

**Comment by drseb** [comment]
IMHO, we should add some equiv-axioms. We have a lot of cancer annotations and want semantic similarity et al. to use this information. Can we skype about this soon?

**Comment by cmungall** [comment]
But should be in the catalog...

**Comment by cmungall** [comment]
On 13 Jun 2016, at 22:56, Sebastian Köhler wrote:

> IMHO, we should add some equiv-axioms. We have a lot of cancer 
> annotations and want semantic similarity et al. to use this 
> information. Can we skype about this soon?

To the already existing HPO classes? Yes, that would be the next stage 
here.

I can't make the friday 8am slot for a call this week, perhaps next 
week. Or if you just want to check in, look for me on skype

**Comment by drseb** [comment]
This has been stale for 3 years now. What is the status of this? Can we close this PR?

**Pull request closed without merging**
