### PR TITLE
Changed definitions to refer to hormones as roles.

### PR DESCRIPTION
**Pull request by balhoff**
This PR updates a few classes to resolve additional incompatibilities between HPO and Uberon. Hormones are roles in CHEBI, and axioms about blood in Uberon allow detecting violations of disjointness.

@cmungall is this the right pattern for hormone roles? Or is there a genus class I should add, e.g. (chemical and 'has role' some hormone).

These definitions use ['has role'](http://purl.obolibrary.org/obo/RO_0000087) from RO, which now will need to be added to ro_import (it doesn't have a label in the diff).

Here is the readable diff:

https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fhuman-phenotype-ontology%2Fraw%2F3d9cf36923b0ec9d854114edf6519716f9dee7cd%2Fsrc%2Fontology%2Fhp-edit.owl&right=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fhuman-phenotype-ontology%2Fraw%2Fchebi-roles%2Fsrc%2Fontology%2Fhp-edit.owl&loadimports=true

### CODE REVIEW

**Comment by balhoff** [comment]
@cmungall is there a genus term to be used with the 'has role' restrictions? Or is these sufficient as they are?

**Comment by pnrobinson** [comment]
@balhoff Are we ready to merge this or what is the plan?

**Comment by drseb** [comment]
How does this align with MP and ZP?

**Comment by balhoff** [comment]
Looks like MP has the same problem. The model I used aligns with ChEBI and GO. Now I remember I need to update ro_import to include has_role, so this should wait on that.

**Comment by balhoff** [comment]
@pnrobinson I think this can be merged now.

**Pull request merged**
