### PR TITLE
Remove redundant GO axioms from hp-edit.owl

### PR DESCRIPTION
**Pull request by matentzn**
Causing some serialisation issues.

### CODE REVIEW

**Comment by matentzn** [comment]
@drseb be careful with who has the hp lock right now. :P

**Comment by drseb** [comment]
why do we have non-hpo-related axioms in hp-edit? Are there more of this?

**Comment by matentzn** [comment]
No idea! Just noticed them during QC.

**Comment by pnrobinson** [comment]
I have the lock but I will let you have it for now OK.

**Comment by drseb** [comment]
ok. let's merge when peter is done. do we need the lock when we have our call @matentzn ?

**Comment by matentzn** [comment]
We dont need a lock necessarily for the meeting. Afterwards.

**Comment by drseb** [comment]
travis failed!?

**Pull request merged**
