### PR TITLE
revise logical def for HP_0000407 'Sensorineural hearing impairment'

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
this is the new logical def: 

'has part' some 
    (absent
     and ('inheres in' some ('sensory perception of sound' and ('occurs in' some nerve)))
     and ('has modifier' some abnormal))

### CODE REVIEW

**Comment by pnrobinson** [comment]
Impairment does not necessarily mean absent -- I think that we can use simply 'reduced' instead of absent'?

**Comment by nicolevasilevsky** [comment]
sounds good!
I was following the pattern used for the parent term HP_0000365 'Hearing impairment'

To be consistent, we should use 'decreased rate' as the quality (instead of 'reduced').

I'll update this for both terms

**Comment by pnrobinson** [comment]
thanks!

**Comment by nicolevasilevsky** [comment]
I'm not sure why the build is failing here
@matentzn @pnrobinson @drseb

**Comment by pnrobinson** [comment]
This is this issue in travis
```
Test: PerformHpoOwlQC
found problematic URIs! Did you use the correct relationship?
 - http://purl.obolibrary.org/obo/pato#towards -> 1
```
I am not sure where this is coming from

**Comment by nicolevasilevsky** [comment]
Ah, I found it, thanks @pnrobinson!

**Pull request merged**
