### PR TITLE
Typo in the definition of HP:0100603 Toxemia of pregnancy: replaced "Ecplamsia" with "Eclampsia".

### PR DESCRIPTION
**Pull request by sdumitriu**

### CODE REVIEW

**Comment by cmungall** [comment]
Thanks!

Is this our first PR on HPO? Cool! Note that if people are switching 
version of Protege arbitrarily we will get some spurious diffs which 
could cause this PR to conflict (in which case it should be easy to 
manually redo Sergiu's changes).

Are you OK to do this @drseb?

**Comment by drseb** [comment]
Yes it is our first PR. The fact that the OWL file looks very different on different machines makes me think that PRs are no good idea for hp-edit.owl. @cmungall  Let's discuss this soon.

**Comment by drseb** [comment]
Thanks @sdumitriu

**Comment by cmungall** [comment]
@drseb - if we get a new Protege release and everyone standardizes on using either this version or a subsequent version the problem will be solved. See https://github.com/owlcs/owlapi/issues/273#issuecomment-128844710

**Pull request merged**
