### PR TITLE
Add EQs to terms without in Abnormal circulating X

### LINKED ISSUE #10321: Issue importing CHEBI terms to add new EQ
@matentzn I need to add new CHEBI terms in order to complete EQs of 'circulating compounds'.
I tried to follow what suggested in #7390 . I added terms to the chebi.txt and ran sh run.sh make refresh-merged.

The import dates changed, but nothing else did. I tried to also then add manually to protoge and then run it, and that didn't work.

I cannot add just the chebi number to the EQ.

Below is a list of terms required.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/carmol/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

CHEBI   Label | CHEBI ID | Syn used in HP
-- | -- | --
3-methyl-2-oxobutanoate | CHEBI:11851
S-adenosyl-L-methionine | CHEBI:15414
2-oxoadipic acid | CHEBI:15753
arachidonic acid | CHEBI:15843
5,6-dihydrouracil | CHEBI:15901
5-oxoproline | CHEBI:16010
guanidinoacetic acid | CHEBI:16344
S-adenosyl-L-homocysteine | CHEBI:16680
guanosine | CHEBI:16750
Glutathione | CHEBI:16856
5-hydroxymethyluracil | CHEBI:16964
biliverdin | CHEBI:17033
D-glucitol 6-phosphate | CHEBI:17044 | sorbitol
5alpha-cholest-7-en-3beta-ol | CHEBI:17168 | lathosterol
N(4)-(beta-N-acetyl-D-glucosaminyl)-L-asparagine | CHEBI:17261
3-(4-hydroxyphenyl)lactic acid | CHEBI:17385 | hydroxyphenyllactic acid
inosine | CHEBI:17596
Octadecatrienoylcarnitine | CHEBI:176718
O-acylcarnitine | CHEBI:176911
N,N-dimethylglycine | CHEBI:17724
desmosterol | CHEBI:17737
thymidine | CHEBI:17748
thymine | CHEBI:17821
4-methyl-2-oxopentanoate | CHEBI:17865
Pipecolic acid | CHEBI:17964
4-hydroxyphenylacetic acid | CHEBI:18101
Manganese atom | CHEBI:18291
Argininosuccinic acid | CHEBI:184023
branched-chain keto acid anion | CHEBI:191201
7-Dehydrocholesterol   5,6-oxide | CHEBI:192164
N-acetyl-L-aspartic acid | CHEBI:21547
aconitic acid | CHEBI:22211
arabinitol | CHEBI:22605
deoxyuridine phosphate | CHEBI:23641
Homoarginine | CHEBI:24606
Hydroxybutyric acid | CHEBI:24684
succinate | CHEBI:26806
very long-chain fatty acid | CHEBI:27283
5,6-dihydrothymine | CHEBI:27468
sitosterol | CHEBI:27693
S-sulfo-L-cysteine | CHEBI:27891
isovaleric acid | CHEBI:28484
farnesol | CHEBI:28600
glycolate | CHEBI:29805
hexacosanoic acid | CHEBI:31009
O-phosphoserine | CHEBI:37712
L-alloisoleucine | CHEBI:43433
methionine S-oxide | CHEBI:49033
Dopa | CHEBI:49168
Fumarate salt | CHEBI:50921
pristanic acid | CHEBI:51340
all-cis-docosa-7,10,13,16-tetraenoic acid | CHEBI:53487 | Adrenal acid
Homovanillic acid | CHEBI:545959
alpha-Neu5Ac-(2->3)-beta-D-Gal-(1->3)-[alpha-L-Fuc-(1->4)]-D-GlcNAc | CHEBI:61793 | carbohydrate antigen 19-9
Gly-Pro | CHEBI:70744
Lathosterone | CHEBI:71550
tiglylglycine | CHEBI:73018
N-nicotinoylglycine | CHEBI:7563 | nicotinurate
O-dodecenoylcarnitin | CHEBI:86065
Pyridinoline | CHEBI:88539
Deoxypyridinoline | CHEBI:89510
suberic acid | CHEBI:9300
D-glyceric acid | CHEBI:32398

</body>

</html>
CHEBI Label	CHEBI ID	Syn used in HP
3-methyl-2-oxobutanoate	CHEBI:11851	
S-adenosyl-L-methionine	CHEBI:15414	
2-oxoadipic acid	CHEBI:15753	
[arachidonic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_15843)	CHEBI:15843 	
[5,6-dihydrouracil](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_15901)	CHEBI:15901	
5-oxoproline	CHEBI:16010	
[guanidinoacetic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_16344)	CHEBI:16344	
S-adenosyl-L-homocysteine	CHEBI:16680	
[guanosine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_16750)	CHEBI:16750	
Glutathione	CHEBI:16856	
[5-hydroxymethyluracil](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_16964)	CHEBI:16964 	
[biliverdin](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17033)	CHEBI:17033	
D-glucitol 6-phosphate	CHEBI:17044	sorbitol
[5alpha-cholest-7-en-3beta-ol ](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17168) 	CHEBI:17168	lathosterol
N(4)-(beta-N-acetyl-D-glucosaminyl)-L-asparagine	CHEBI:17261	
[3-(4-hydroxyphenyl)lactic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17385)	CHEBI:17385 	hydroxyphenyllactic acid
[inosine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17596)	CHEBI:17596 	
[Octadecatrienoylcarnitine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_176911)	CHEBI:176718	
[O-acylcarnitine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_176911)	CHEBI:176911	
[N,N-dimethylglycine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17724)	CHEBI:17724	
[desmosterol](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17737)	CHEBI:17737 	
[thymidine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17748)	CHEBI:17748	
[thymine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17821)	CHEBI:17821	
4-methyl-2-oxopentanoate	CHEBI:17865	
Pipecolic acid	CHEBI:17964	
4-hydroxyphenylacetic acid	CHEBI:18101	
Manganese atom	CHEBI:18291	
Argininosuccinic acid	CHEBI:184023	
branched-chain keto acid anion	CHEBI:191201	
7-Dehydrocholesterol 5,6-oxide 	CHEBI:192164	
[N-acetyl-L-aspartic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_21547)	CHEBI:21547	
[aconitic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_22211)	CHEBI:22211 	
[arabinitol](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_22605)	CHEBI:22605	
[deoxyuridine phosphate](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_23641)	CHEBI:23641	
Homoarginine	CHEBI:24606	
Hydroxybutyric acid	CHEBI:24684	
[succinate](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_26806)	CHEBI:26806	
[very long-chain fatty acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_27283)	CHEBI:27283	
[5,6-dihydrothymine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_27468)	CHEBI:27468	
[sitosterol](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_27693)	CHEBI:27693	
[S-sulfo-L-cysteine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_27891)	CHEBI:27891	
[isovaleric acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_28484)	CHEBI:28484	
[farnesol](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_28600)	CHEBI:28600	
[glycolate](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_29805)	CHEBI:29805	
[hexacosanoic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_31009)	CHEBI:31009	
O-phosphoserine	CHEBI:37712	
[L-alloisoleucine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_43433)	CHEBI:43433	
[methionine S-oxide](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_49033)	CHEBI:49033	
Dopa	CHEBI:49168	
Fumarate salt	CHEBI:50921	
[pristanic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_51340)	CHEBI:51340	
[all-cis-docosa-7,10,13,16-tetraenoic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_53487)	CHEBI:53487	Adrenal acid
Homovanillic acid	CHEBI:545959	
alpha-Neu5Ac-(2->3)-beta-D-Gal-(1->3)-[alpha-L-Fuc-(1->4)]-D-GlcNAc	CHEBI:61793	carbohydrate antigen 19-9
Gly-Pro	CHEBI:70744	
Lathosterone	CHEBI:71550	
[tiglylglycine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_73018)	CHEBI:73018	
[N-nicotinoylglycine](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_7563)	CHEBI:7563	nicotinurate
O-dodecenoylcarnitin	CHEBI:86065	
Pyridinoline	CHEBI:88539	
[Deoxypyridinoline ](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_89510)	CHEBI:89510 	
[suberic acid](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_9300)	CHEBI:9300	
D-glyceric acid	CHEBI:32398

### PR DESCRIPTION
**Pull request by LCCarmody**
This will close #10321

### CODE REVIEW

**Comment by LCCarmody** [comment]
@matentzn I am so not confident with doing rebase. I believe the issue is the updating the chebi imports at the beginning (which maybe I should have merged first before making all other changes?) Anyways, can you help?

**Comment by matentzn** [comment]
@LCCarmody dealing with this now, 20 min.

**Comment by matentzn** [comment]
@LCCarmody QC is failing because of a bug in the EQs, but the branch is rebased and the import refreshed.

**Comment by LCCarmody** [comment]
Thanks!! I'll fix

**Pull request merged**
