### PR TITLE
Classes moved from edit to patterns file

### PR DESCRIPTION
**Pull request by matentzn**
This PR contains 243 EQ definitions that moved from the edit file to their pattern directory - without any alteration (i.e. the EQ is exactly the same as it was).

### CODE REVIEW

**Comment by matentzn** [comment]
Yes, I fixed it, but needs some other changes to be merged first.

**Comment by matentzn** [comment]
@drseb This is ready for merge when the QC has finished running! Thanks!

**Comment by drseb** [comment]
The label DO NOT MERGE irritates me. Is this label still up-to-date?

**Comment by matentzn** [comment]
Whoops no! Can be merged!

**Pull request merged**
