### PR TITLE
revise logical def for HP_0012418 "Hypoxemia

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@matentzn @balhoff would one of you mind double checking the logical defs I revised?
thanks!

**Comment by matentzn** [comment]
This looks great, just noticed you added one new EQ that was not previously there. That intended?

**Comment by nicolevasilevsky** [comment]
yes, I intentionally added a new EQ. If a term can have a logical def, we should add one, right?

**Comment by nicolevasilevsky** [comment]
thanks for checking, I'll merge

**Comment by matentzn** [comment]
Then I approve!!

**Comment by balhoff** [comment]
Here is a diff: https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fhuman-phenotype-ontology%2Fraw%2F20066a74f144c53806ea7f81ff6d4ab79c5b8ea2%2Fsrc%2Fontology%2Fhp-edit.owl&right=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fhuman-phenotype-ontology%2Fraw%2F33cd534a388ecf957514058848a3bbbea466d4ca%2Fsrc%2Fontology%2Fhp-edit.owl&loadimports=true

It takes a little while to load.

**Pull request merged**
