### PR TITLE
obsolete/merge Anti-type I liver-kidney microsomal antibody positivity

### LINKED ISSUE #7579: HP:0030908 and HP:0034113 seem to describe the same finding / result
**HPO term**
HP:0030908 and HP:0034113

**Bug description**
These seem to describe the same finding / result.  Keeping HP:0030908 may make most sense because UMLS characterized it as a finding, but characterized HP:0034113 as a Lab Result, and therefore it doesn't get into MedGen.  For the long run, I am discussing with MedGen whether they should import not only HPO-derived findings but also HPO-derived test results, but that change won't happen instantly.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #7579

### CODE REVIEW

**Comment by pnrobinson** [comment]
@matentzn can you take a look at this? On my side I get
###########################################################
########  HPO QUALITY CONTROL: PASSED  ####################
###########################################################
but for some reason the CI is throwing an error.

**Comment by matentzn** [comment]
I will take care of it tomorrow.

**Comment by matentzn** [comment]
THAT is why some of your commit break the master branch! It is my fault!! Your qc script was not _stopping_ when it failed for ODK-based quality control. I have now pushed this change on this branch here to be sure you see these things!

The current issue 1 seems to be an undesired logical equivalence:

```
ERROR Equivalence: <http://purl.obolibrary.org/obo/HP_0000130> == <http://purl.obolibrary.org/obo/HP_0031105>
```

As well is some wrong obsoletions and deprecations (which are not caused by Nicole, but I think you could fix them?)

```
ERROR	duplicate_label	HP:0000130	rdfs:label	Abnormal uterus morphology
ERROR	duplicate_label	HP:0031105	rdfs:label	Abnormal uterus morphology
ERROR	misused_obsolete_label	HP:0012369	rdfs:label	obsolete Abnormal malar bone morphology
ERROR	misused_replaced_by	HP:0012369	IAO:0100001	HP:0010668
```

**Comment by nicolevasilevsky** [comment]
@pnrobinson Nico and I fixed this issue- we reverted the  label of HP:0000130 back to Abnormality of the uterus

Nico fixed the hp-quality check so it now fails when there is failure (on this PR, so we need to merge this PR for it work)

**Pull request merged**
