### PR TITLE
DO NOT MERGE YET: Activate SPARQL checks

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
Note this currently fails travis - *this is expected*. The ontology should be fixed such that it conforms to these tests, then we can make this live

**Comment by drseb** [comment]
But in github it says, **All checks have passed**. What are you referrring to, when you say 

> Note this currently fails travis

?

**Comment by cmungall** [comment]
Ah, I didn't realize we weren't actually doing a `make test`

I can go ahead and make changes to .travis.yml but I feel it may be beneficial for us to talk briefly first so we're on the same page

**Comment by cmungall** [comment]
we'll also want to add standard reasoner tests too, but this will depend on https://github.com/obophenotype/upheno/issues/149 being completed

**Comment by matentzn** [comment]
Should be closed (not merged) as soon superceded by proper ODK config.

**Pull request closed without merging**
