### PR TITLE
Replaced ro_extra by ro_import

### PR DESCRIPTION
**Pull request by matentzn**
https://github.com/obophenotype/human-phenotype-ontology/issues/4277

### CODE REVIEW

**Comment by drseb** [comment]
Did you do a reasoner diff as suggested by @cmungall in  https://github.com/obophenotype/human-phenotype-ontology/issues/4277#issuecomment-451614363 ?

**Comment by matentzn** [comment]
Yes! the only effect came from ro itself. nothing from these few extra axioms..

**Comment by matentzn** [comment]
@pnrobinson okay to be merged?

**Comment by pnrobinson** [comment]
Thanks Seb! Can we also delete the branch (there are a few other old ones too)?

**Comment by matentzn** [comment]
one of them is now obsolete. The other one has a lot of information we might wont to re-use when we get to the issue of neoplasms.

**Comment by drseb** [comment]
@matentzn

**Comment by drseb** [comment]
ah sorry. I see you removed. Forget it - a bit tired today

**Comment by matentzn** [comment]
It was. :P sparql checks are all implemented on the other branch (odk-hp) now.

**Pull request merged**
