### PR TITLE
Switched BFO:quality to PATO:quality in definitions

### PR DESCRIPTION
**Pull request by matentzn**
- Switched BFO quality to PATO:quality in 14 definitions.
- Switched definition of 'Abnormal heart morphology' (HP_0001627) from BFO:quality to PATO:morphology to avoid 4 indesirable inference that would occur if the definition would be simply switched to PATO:quality:

```
'Absent atrioventricular node' -> 'Abnormal heart morphology'
'Ventricular tachycardia' -> 'Abnormal heart morphology'
'Ventricular fibrillation' -> 'Abnormal heart morphology'
'Abnormal heart valve physiology' -> 'Abnormal heart morphology'
```

All 15 changes now result in two new inferrences (subsumptions):

```
'Pectoral muscle hypoplasia/aplasia' -> 'Abnormality of axial muscles'
'Poor suck' -> 'Abnormal consumption behavior'
```

### CODE REVIEW

**Comment by pnrobinson** [comment]
Looks great, I will look on Monday.
One comment is that we are trying to better distinguish between morphology, functionality, and quality in the HPO hierarchy and term structures, and there may be some legacy definitions that have "quality" where they should have "morphology" or "functionality" -- we should be on the lookout for them!

**Comment by matentzn** [comment]
Sidenote: can one of you *delete* the branch called ***'quality-pfo-to-pato'*** (pfo instead of bfo), which I created before realising my text editor changed hp-edit whitespace in too many places.

**Comment by pnrobinson** [comment]
@matentzn do you mean just delete the branch entirely and you will make a new one? i./e.,do not accept this PR?

**Comment by matentzn** [comment]
No no! There is a second branch called *'quality-pfo-to-pato'* (pfo instead of bfo) I created yesterday, not this one. The other one needs to be deleted. This one here needs to be merged :)

**Pull request merged**
