### PR TITLE
replaces MPATH with NCIT where replacement available, fixes #1092

### LINKED ISSUE #1092: Replace usage of MPATH with NCIT
3rd item here: https://github.com/obophenotype/upheno/issues/166

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
I got the +1 from Peter, so merged

**Comment by drseb** [comment]
Hmm... so how do we map from mpath to ncit? Did we just loose interoperability to MP?

**Comment by cmungall** [comment]
No - see the parent ticket: https://github.com/obophenotype/upheno/pull/167

We have retained equivalency - admittedly we have introduced an extra moving part though

**Comment by drseb** [comment]
hm.. ok. sounds good

**Pull request merged**
