### PR TITLE
add fractured terms and new proportion terms

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by matentzn** [comment]
@nicolevasilevsky what is the status of this? Is this the most up to date version of the fractures and proportion branch? Are we waiting for something?

**Comment by nicolevasilevsky** [comment]
We were waiting for @pnrobinson and @drseb to sign off

**Comment by matentzn** [comment]
Ah ok, great, thanks!

@pnrobinson @drseb you can find the latest builds of this here:
https://ci.monarchinitiative.org/view/pipelines/job/hpo-pipeline-dev2/lastSuccessfulBuild/artifact/

I would suggest you review hpo-full.owl for the classification, or 
https://ols.monarchinitiative.org/ontologies/hp

If I can help with making the review easier, like providing a table of terms or something, let me know.

**Comment by pnrobinson** [comment]
@matentzn @drseb  it would be great if we could discuss this before moving forward. If it is easy to make a CSV for review that would be great. Also to review the scripts used to generate the suggested new terms?

**Comment by matentzn** [comment]
There are not really any scripts:

These are the patterns we used:
http://purl.obolibrary.org/obo/upheno/patterns-dev/brokenAnatomicalEntity.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/fracturedAnatomicalEntity.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/fracturedAnatomicalEntityByFractureType.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalProportionOfCellTypeInLocation.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalProportionOfCellTypeTowardsCellTypeInLocation.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedProportionOfCellTypeInLocation.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedProportionOfCellTypeTowardsCellTypeInLocation.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedProportionOfCellTypeInLocation.yaml
http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedProportionOfCellTypeTowardsCellTypeInLocation.yaml

And that's basically all there is to it: compiling a table against one of these patterns.

Here is a table you can use to guide your review process:
https://github.com/obophenotype/human-phenotype-ontology/blob/fractures-2/src/ontology/reports/hpo_dosdp_table.csv

(Note there are duplicate rows because some terms have multiple synonyms).

Let me know if there is anything else I can do to help.

I would:
1. Check the term table (labels and definitions).
2. Eyeball the hierarchies here: https://ols.monarchinitiative.org/ontologies/hp
3. When you are happy, I will (against my better judgement), assert the inferred hierarchies for the new terms (only for those). Then its done!

**Comment by pnrobinson** [comment]
@matentzn  I think the fractures need a lot of work still. Can we try and finish the immune cells first and remove the fractures from this PR.

For instance, this pattern file is inconsistent (https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/fracturedAnatomicalEntityByFractureType.yaml) because the term label does not include the fracture type.
Also, there are not nearly enough bones.

**Comment by matentzn** [comment]
> Also, there are not nearly enough bones. 

@nicolevasilevsky @callahantiff, you should double-check that all the pattern tsvs are complete. I can't find a single fracturedAnatomicalEntityByFractureType.csv for example!

> For instance, this pattern file is inconsistent (https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/fracturedAnatomicalEntityByFractureType.yaml) because the term label does not include the fracture type.

It does!

```
name:
  text: "%s %s"
  vars:
   - fractured
   - anatomical_entity
```

fractured is a variable, which is the fracture type! But there are no classes with a fracture type, so something must be wrong (@nicolevasilevsky )

> Can we try and finish the immune cells first and remove the fractures from this PR.

We absolutely can! Let me know @pnrobinson when they are good to go.

**Comment by nicolevasilevsky** [comment]
hi - sorry for the delayed reply. 

@matentzn could you point me to the TSV files? Sorry, I don't remember where they are filed (I don't see them in the github repo.)

We didn't add new fracture terms for all of the bones in the body, just the bones that were relevant in @callahantiff's [data set](https://docs.google.com/spreadsheets/d/11Z6RoYvbo2-_YwRTve0iG3bINnHRlw6jga_j0Oy7_1A/edit#gid=1472378467).

**Comment by matentzn** [comment]
As per slack discussion, they are on the branch in the src/patterns/data directories. @pnrobinson `Also, there are not nearly enough bones.` -> Seems like @nicolevasilevsky and @callahantiff included only the 105 fracture types that were strictly necessary for her work, not all the bones.

So I wait now for your "GO" regarding the proportion terms, and will merge them in, so that this pull request can be only about the fractures.

**Comment by pnrobinson** [comment]
Can we zoom about this?

**Comment by nicolevasilevsky** [comment]
of course, I'll coordinate with Kristen to set up a meeting.

**Pull request merged**
