### PR TITLE
Add DOSDP matches pipeline

### PR DESCRIPTION
**Pull request by matentzn**
This PR:

- adds a new matching pipeline to HPO that translates the EQ axioms into TSV files.
- this pipeline is documentative right now, so does not, at all, affect the HPO pipeline other than providing tables with pattern matches.
- It is the first step in a pipeline that ensures that we slowly curate classes that do not have matches.

### CODE REVIEW

**Comment by pnrobinson** [comment]
@matentzn  what should we do with this? Has this gotten a bit stale?

**Comment by matentzn** [comment]
No not stale, and still relevant. I will put it up my list again - we need it for our EQ review process.

**Comment by pnrobinson** [comment]
@matentzn slowly but steadily working for issue inbox zero - is there progress with this? :-0

**Comment by matentzn** [comment]
@pnrobinson ok updated description. You can merge this.

**Pull request merged**
