### PR TITLE
new terms for bilateral cleft lips

### PR DESCRIPTION
**Pull request by sabrinatoro**
The orofacial team needs more terms to annotate 'bilateral cleft'. In this PR:
- more specific 'bilateral cleft' terms
- terms to specify complete/incomplete/microform cleft lip to be used with the left/right modifiers** to describe bilateral cleft
- changed of complete/incomplete cleft maxillary alveolar ridge to allow more flexibility of annotations

**the current "complete/incomplete/microform unilateral cleft lip" terms were problematic in describing bilateral cleft since the definition notes that it is ONLY on one side.

### CODE REVIEW

**Comment by sabrinatoro** [comment]
If this ontology organization is accepted, we would create the same organization for the "cleft maxillary alveolar ridge".

**Comment by pnrobinson** [comment]
At various meetings in Europe -- I will take a look at this on Monday!
PRs are the worst way of doing this because it is rather laborious to look at changes. It would be better just to make detailed issues!

**Comment by matentzn** [comment]
We need to make this easier then - maybe some sop with screenshots and a nicer diff. But we should have more than just you being able to edit HPO, don't you think?

**Comment by sabrinatoro** [comment]
Let's set a meeting to discuss this and get the changes needed (there are more changes required, not shown in this PR).

I know this work is not the priority for the HPO grant, but I really need this part of the ontology reviewed for the orofacial project I am working on. I don't mind "how" we want to proceed, I just need the revisions in the ontology to be done. 

I will schedule a meeting where we (Peter and I and possibly the experts, though they have already given their input) can discuss and make the changes, and push. How does it sound?

**Comment by pnrobinson** [comment]
@sabrinatoro @matentzn I think the best way of doing this is some combination of robot templates and issues. The PR with changes in an OWL file is incredibly painful, especially if it is multiple new terms -- there is hardly any way of actually seeing just the changes.

**Pull request merged**
