### PR TITLE
Hotfix to ensure synonym is in fact a comment

### PR DESCRIPTION
**Pull request by matentzn**
From HPO mailing list discussion

@pnrobinson I assume you have made the appropriate changes in hp-edit.owl

### CODE REVIEW

**Comment by pnrobinson** [comment]
@matentzn  -- I fixed the synonyms in hp-edit.owl and push/merged the other PR. Does this PR include the corresponding fixes in the generated files? I wonder if it would be better to regenerate those files now after the fix, since there were three kinds of error -- unless this PR has telepathic powers!?

**Comment by matentzn** [comment]
Ok, up to you.. That will not be exactly a "hotfix", because of the other changes you have applied in the meantime, but if you feel better this way, ok. I will then have to do another release as well, due to the changed version numbers in the files and the necessity to re-route the versioned PURL to the correct place. I hope that is ok.

**Comment by matentzn** [comment]
Its done.. So check the diff and see if you want it!

**Comment by pnrobinson** [comment]
thanks!

**Pull request merged**
