### PR TITLE
HPO QC pipeline migrated to single script

### PR DESCRIPTION
**Pull request by matentzn**
This can also be run locally using the following command:

```
cd src/ontology
sh hp-qc-pipeline.sh
```

### CODE REVIEW

**Comment by matentzn** [comment]
The pipeline runs locally, but maybe the only thing I did not do quite as it was was that previously, your variables where environment variables; now they are only shell variables. For most of them, I think that it does not matter, but maybe for JAVA_OPTS it does, because I dont see it used in the code. In this case, I would just change the script to EXPORT JAVA_OPTS.

**Comment by matentzn** [comment]
I merged this for now, as it does not disrupt the any of the HP pipelines.

**Comment by drseb** [comment]
Does this still stop in case one of the first steps fails or does it mean the whole script runs and then the result is derived by travis? This would have serious consequences on the runtime of the QC, which I would like to avoid.

Seb

**Comment by matentzn** [comment]
Travis is unchanged (it is not using the script); this is just an additional script that Peter can run locally to run QC.. And yes, it fails when something along the path fails! (`set -e`). You could try it out if you want;

```
cd src/ontology
sh hp-qc-pipeline.sh
```

**Comment by drseb** [comment]
Ah okay. Thanks a lot. 

Sent from mobile

**Pull request merged**
