### PR TITLE
Add 437 new british synonyms to HPO

### PR DESCRIPTION
**Pull request by matentzn**
Please review this carefully before merging! 

@pnrobinson 
@drseb 
@nicolevasilevsky

### CODE REVIEW

**Comment by pnrobinson** [comment]
Could you send a TSV file with the new synonyms? It is impossible to check this with the OWL file!

**Comment by drseb** [comment]
Is there a reason to use 
`...#hasSynonymType> "http://purl.obolibrary.org/obo/HP_0045076"^^xsd:string)`

instead of 
`#hasSynonymType> <http://purl.obolibrary.org/obo/HP_0045077>` ?

Currently the HPO-QC marks those as mistake.

**Comment by matentzn** [comment]
Thanks! I hope thats fixed now! I hope you meant `#hasSynonymType> <http://purl.obolibrary.org/obo/HP_0045076>` (not 77) 

Lets see what QC says!

**Comment by drseb** [comment]
of course. just the IRI stuff

**Comment by matentzn** [comment]
Comments of pipeline:

```
Found problem in Term : Color vision defect (HP:0000551)
 - List of synonyms contains duplicated entries
Found problem in Term : Subconjunctival hemorrhage (HP:0011896)
 - List of synonyms contains duplicated entries
Found problem in Term : Hemorrhage of the eye (HP:0011885)
 - List of synonyms contains duplicated entries
Found problem in Term : Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection (HP:0011550)
 - Synonym is more than 90 characters long. Looks wrong! biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connexion
```

I think the first three are all cases where the british spelling annotation is the same as another kind of synonym (hasRelatedSynonym).

The last one is your call. Either change QC or remove this synonym! @drseb

**Comment by matentzn** [comment]
@drseb do you want me to:

1) remove hasRelatedSynonym where a british spelling exact synonym exists?
2) Remove the long synonym for now?

**Comment by drseb** [comment]
Why is this synonym so long? Isn't it derived from an existing one?
In any case, I vote for removing such long synonyms.

**Comment by matentzn** [comment]
This is no problem but let’s be clear: if there is an HPO term with a label, not synonym, that has more than 90 chars, we won’t create a British synonym for it using the automated pipeline?

**Comment by pnrobinson** [comment]
@drseb -- which synonym?

**Comment by matentzn** [comment]
Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection (HP:0011550)

**Comment by drseb** [comment]
yes. in my opinion something is usually strange when a label or synonym is this long.

**Comment by drseb** [comment]
@pnrobinson we are discussing this comment: https://github.com/obophenotype/human-phenotype-ontology/pull/5111#issuecomment-575529665

**Comment by matentzn** [comment]
Oops I didnt read the threads correctly and I thought Peters "I agree" on another thread was the response here. In any case, I expanded the pipeline to allow for configuring a maximum synonym length. I would still suggest to consider that perhaps the label is also too long for the above term.. In any case, I have now removed this synonym, and I know exclude all synonyms longer than X, where X is configured to be 90.

**Comment by matentzn** [comment]
Ok for the busy people, here a summary of all of the above and decisions that need to be made:

- synonyms longer than 90 characters are excluded by the pipeline
- the remaining 3 errors come from the fact that there are 'relatedSynonyms'. I suggest  to remove the 'related synonyms' in all 3 cases, so that we only have the 'exactSynonyms'
- Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection (HP:0011550) is a very long _label_ and we should consider to make it shorter (independent of this Pull request).

**Comment by drseb** [comment]
Yes to all three! Thanks

**Comment by pnrobinson** [comment]
Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connection -> This is what the cardiologists proposed. We may need to revisit how we are coding this (it is obviously a bundled term). We will hopefully be doing a cardiology workshop, but let's leave this for now. Agree to the other items!

**Comment by matentzn** [comment]
@drseb This is now ready to be merged at your own discretion.

**Pull request merged**
