### PR TITLE
Fix #9953, fix #9978 - obsolete label 4000080 reintroduced

### LINKED ISSUE #9953: Term made obsolete recently is missing name key/value in the hpo.obo file
**HPO term**: HP:4000080

**Bug description**: The term present on the hpo.obo file is missing the **name** key/value.

I believe it should be:

```
[Term]
id: HP:4000080
name: obsolete Reduced attempt to get or direct another's attention
is_obsolete: true
replaced_by: HP:5200027
```

But it is:

```
[Term]
id: HP:4000080
is_obsolete: true
replaced_by: HP:5200027
```

Thank you so much in advance!

### LINKED ISSUE #9978: HP:4000080 missing label
We hit a problem importing DECIPHER to the latest HPO version because
the deprecated term HP:4000080 doesn't have a label listed in hp.owl.
The entry looks like this:

    

    <owl:Class rdf:about="[http://purl.obolibrary.org/obo/HP_4000080">](http://purl.obolibrary.org/obo/HP_4000080%22%3E)
        <obo:IAO_0100001>HP:5200027</obo:IAO_0100001>
        <owl:deprecated
rdf:datatype="[http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>](http://www.w3.org/2001/XMLSchema#boolean%22%3Etrue%3C/owl:deprecated%3E)
    </owl:Class>

### PR DESCRIPTION
**Pull request by dnil**
Attempt to add back a label for HP:4000080. The missing label is bugging the data model of a couple of systems downstream.
 
- Fix #9953 
- Fix #9978

### CODE REVIEW

**Comment by pnrobinson** [comment]
This was fixed with recent merge.

**Comment by meladawy** [comment]
@pnrobinson We have the same issue of a missing label for 4000080. This PR seems to be closed without being merged. Would you please point us to the other recent merge that includes fix for this, and whether it's included in 2023-10-09 Release?

Thank you!

**Comment by pnrobinson** [comment]
The fix will be included in the next release. If you need this right away let me know and I will point you to directions for making a local version of hp.json from the hp-edit.owl file, which always contains the very latest version of everything, including this fix.

**Comment by meladawy** [comment]
Thanks @pnrobinson for the quick response. I think we can wait until the next release.

**Pull request closed without merging**
