### PR TITLE
New exact UK synonyms to be added after running pipeline

### PR DESCRIPTION
**Pull request by matentzn**
| ID | Synonym |
| --- | --- |
| HP:0002094 | Dyspnoea |
| HP:0002121 | Generalised non-motor (absence) seizure |
| HP:0002140 | Ischaemic stroke |
| HP:0002326 | Transient ischaemic attack |
| HP:0002608 | Coeliac disease |
| HP:0002626 | Venous varicosities of coeliac and mesenteric vessels |
| HP:0002642 | Arteriovenous fistulas of coeliac and mesenteric vessels |
| HP:0002875 | Exertional dyspnoea |
| HP:0005531 | Biphenotypic acute leukaemia |
| HP:0007634 | Nonarteritic anterior ischaemic optic neuropathy |
| HP:0010818 | Generalised tonic seizure |
| HP:0011173 | Focal behaviour arrest seizure |
| HP:0011550 | Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connexion |
| HP:0012326 | Abnormal coeliac artery morphology |
| HP:0012327 | Coeliac artery compression |
| HP:0012763 | Paroxysmal dyspnoea |
| HP:0025190 | Bilateral tonic-clonic seizure with generalised onset |
| HP:0032570 | Pontine ischaemic lacunes |
| HP:0032637 | Renal interstitial oedema |
| HP:0032789 | Focal aware behaviour arrest seizure |
| HP:0032790 | Focal impaired awareness behaviour arrest seizure |
| HP:0032823 | Neonatal electro-clinical seizure with behaviour arrest |
| HP:0100858 | Dilatation of coeliac artery |

### CODE REVIEW

**Comment by matentzn** [comment]
You can review the list but don’t merge yet @pnrobinson just give me the go. Forgot we had standardised our annotation properties!

**Comment by matentzn** [comment]
This can now be merged.

**Comment by pnrobinson** [comment]
@matentzn 
HP:0011550 | Biventricular heart with straddling right sided atrioventricular valve and absent left sided atrioventricular connexion

AFAIK connexion with 'x' is rare even in the UK and thus I am guessing that we would not want to add this as a synonym that would replace "connection" (in other words, if a British system wanted to change spellings to UK automatically using our synonyms, I think they still might prefer to see connection and not connexion, which is simply an archaic form that has survived a bit longer in the UK).

See: https://www.quora.com/What-is-the-difference-between-connection-and-connexion

**Comment by pnrobinson** [comment]
ps everything else is perfect!

**Comment by matentzn** [comment]
Ok, do you want me to:

1) Skip the translation of connection to connexion entirely and remove from pipeline for good
2) Remove all 16 UK synonyms using the term connection
3) Both of the above
4) Just remove the new synonym mentioning the term connexion

These are 16 UK synonyms with the word connexion currently:

| ID | UK SYN |
| ---- | ---- |
| HP:0011545 | Abnormal connexion of the cardiac segments |
| HP:0011546 | Abnormal atrioventricular connexion |
| HP:0011547 | Absent left sided atrioventricular connexion |
| HP:0011548 | Absent right sided atrioventricular connexion |
| HP:0011549 | Univentricular heart with absent left sided atrioventricular connexion |
| HP:0011551 | Right sided atrium to left ventricle and absent left sided atrioventricular connexion |
| HP:0011552 | Ambiguous atrioventricular connexion |
| HP:0011553 | Discordant atrioventricular connexion |
| HP:0011554 | Double inlet atrioventricular connexion |
| HP:0011563 | Abnormal ventriculoarterial connexion |
| HP:0011688 | Supraventricular tachycardia with an accessory connexion mediated pathway |
| HP:0011689 | Supraventricular tachycardia with a concealed accessory connexion |
| HP:0011719 | Supracardiac total anomalous pulmonary venous connexion |
| HP:0011720 | Cardiac total anomalous pulmonary venous connexion |
| HP:0011721 | Infracardiac total anomalous pulmonary venous connexion |
| HP:0011722 | Mixed total anomalous pulmonary venous connexion |

**Comment by matentzn** [comment]
@pnrobinson Have you decided how to proceed?

**Comment by pnrobinson** [comment]
Not sure I understand the question. I would say that connexion can also be a US spelling, so we can leave it as a synonym but not label as UK because both sides of the pond will want to see connection.
I would definitely remove connection to connexion from the mapping file!

**Comment by matentzn** [comment]
We are only talking about synonyms here! I would never change any labels, so my question was about whether you wanted to keep existing synonyms using the word connexion (that is the second table in this pull request - a list of synonyms using the term connexion)  or not. Seems you are fine with that then! Ok I will remove this entry from the dictionary.

**Pull request merged**
